<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Nexus.Products.Chat.Architecture.Tests</RootNamespace>
    <AssemblyName>Nexus.Products.Chat.Architecture.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nexus.Products.Chat.Api\Nexus.Products.Chat.Api.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Products.Chat.Application\Nexus.Products.Chat.Application.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Products.Chat.Domain\Nexus.Products.Chat.Domain.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Products.Chat.Infrastructure\Nexus.Products.Chat.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.1" />
  </ItemGroup>

</Project>

